---
title: "Législatives 2024"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti 
---


<style>
  body {
    background-color: #99d6eb;
  }
</style>

# Tour 1{data-navmenu=France}

```{r}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
```

```{r Liste des package, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse) 
library(plotly)
library(knitr)
library(readr)
library(kableExtra)
library(ggplot2)
library(ggridges)
library(tidyr)
library(readr)
library(dplyr)
library(forcats)
library(scales)
library(patchwork)
library(flexdashboard)
library(cartography)
library(leaflet)
library(readxl)
library(shiny)
library(sf) 
library(DT)
library(htmltools)
```

Column {data-width=1000}
-----------------------------------------------------------------------
### Inscrits
```{r}
valueBox(
  value = tags$span("49.332.709", style = "color: black;"), 
  caption = tags$span("Inscrits", style = "color: black;"),  
  icon = "fa-user", 
  color = "#00ffff") 
#Les logos avec le france_entiere$Inscrits donc on a préféré écrire les valeurs manuellement
```

### 

```{r, echo=FALSE, warning = FALSE, message = FALSE}

Palette1 <- c("#DAF7F0" ,"#82C6CC","#3396A3","#087D8B","#004C63")


résultats_régions <- read.csv(file = "resultats-definitifs-par-regions.csv", 
                              sep = ";", 
                              header = TRUE,
                              stringsAsFactors = FALSE, 
                              fill = TRUE)


regions_fr <- st_read("regions.geojson", quiet = TRUE)

data_régions <- résultats_régions %>%
  select(Libellé.région, X..Votants, X..Abstentions) %>%
  rename(region = Libellé.région, taux_part = X..Votants, taux_absenteisme = X..Abstentions) 

regions_fr <- regions_fr %>%
  left_join(data_régions, by = c("nom" = "region"))
```


```{r}
getColor <- function(taux_part) {
  if (taux_part < 40) {
    return(Palette1[1])
  } else if (taux_part < 50) {
    return(Palette1[2])
  } else if (taux_part < 60) {
    return(Palette1[3])
  } else if (taux_part < 70) {
    return(Palette1[4])
  } else if (taux_part < 80) {
    return(Palette1[5])
    }
}

regions_fr$color <- sapply(regions_fr$taux_part, getColor)

leaflet(regions_fr) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~color,  
    color = "black", weight = 1, opacity = 1, fillOpacity = 0.7,
    highlight = highlightOptions(weight = 2, color = "white", bringToFront = TRUE),
    label = ~paste(nom, ": ", taux_part, "", sep = ""), 
    popup = ~paste(
      "<strong>Région :</strong> ", nom, "<br>",
      "<strong>Taux de participation :</strong> ", taux_part, "<br>",
      "<strong>Taux d'absentéisme :</strong> ", taux_absenteisme, "<br>"
    )
  ) %>%
  addLegend(
    colors = Palette1, 
    labels = c("< 40%","< 50%", "< 60%", "< 70%", "< 80%"),
    opacity = 0.7, title = "Taux de participation (%)",
    position = "bottomright"
  )

```

Column {data-width=1000}
-----------------------------------------------------------

### Votants
```{r}
valueBox(
  value = tags$span("32.908.657"),  
  caption = tags$span("Votants TOUR 1"),  
  icon = "fa-envelope", 
  color = "#4040fb" 
)

```

###

```{r, include=FALSE, echo=FALSE}
france_entiere <- read_excel("resultats-definitifs-france-entiere.xlsx")

```

```{r}

Palette1 <- c("#DAF7F0", "#82C6CC", "#3396A3", "#087D8B", "#004C63")

graph_votants <- ggplot(résultats_régions, 
  aes(
    x = fct_reorder(Libellé.région, Votants),  
    y = Votants, 
    fill = Votants,  
    text = paste("Nombre de votants:", Votants)
  )
) + 
  geom_bar(stat = "identity", alpha = 0.8) +  
  coord_flip() +  
  theme_minimal() +  
  theme( 
    legend.position = "none",  
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),  
    axis.title.x = element_blank(), 
    axis.title.y = element_text(size = 8), 
    axis.text.x = element_text(size = 5), 
    axis.text.y = element_text(size = 10, hjust = 0),
    plot.title = element_text(hjust = 0.5, size = 12), 
    plot.subtitle = element_text(hjust = 0.5, size = 10),  
    plot.margin = margin(t = 20, r = 10, b = 10, l = 10)) + 
  labs(
    title = "Régions et Votes : La Bataille des Urnes",
    subtitle = "Visualisation des effectifs des votants par régions", 
    x = "", 
    y = "Nombre de votants"
  )+
  scale_fill_gradientn(colors = Palette1) +  
  scale_y_continuous(labels = NULL)

graph_votants_interactif <- ggplotly(graph_votants, tooltip = "text") %>%
  config(displayModeBar = FALSE) %>%
  layout(
    title = list(
      text = "<b>Régions et Votes : La Bataille des Urnes</b><br><sup>Visualisation des effectifs des votants par régions</sup>",
      x = 0.1,  
      xanchor = "center",
      yanchor = "top"
    )
  )
  
graph_votants_interactif
```


Column {data-width=1000}
-----------------------------------------------------------

### Abstentions
```{r}
valueBox(
  value = tags$span("16.424.052", style = "color: black;"),  
  caption = tags$span("Abstentions TOUR 1", style = "color: black;"),  
  icon = "fa-times", 
  color = "#fa5252"  
)

```

###

```{r, include=FALSE, echo=FALSE}
france_entiere <- read_excel("resultats-definitifs-france-entiere.xlsx")

```

```{r}

nuances <- france_entiere %>% select(starts_with("Nuance candidat"))
voix <- france_entiere %>% select(starts_with("Voix"))

resultats_candidats <- data.frame(
  Nuance = unlist(nuances),
  Voix = as.numeric(unlist(voix))
)

resultats_candidats <- resultats_candidats[resultats_candidats$Voix > 0, ]

resultats_groupes <- resultats_candidats %>%
  group_by(Nuance) %>%
  summarise(Total_Voix = sum(Voix))

total_voix_exprimees <- sum(resultats_groupes$Total_Voix)
resultats_groupes <- resultats_groupes %>%
  mutate(Pourcentage = (Total_Voix / total_voix_exprimees) * 100)
# Harmonisation des catégories entre case_when et couleurs_groupes
resultats_groupes <- resultats_groupes %>%
  mutate(Categorie = case_when(
    Nuance %in% c("RN", "REC", "EXD") ~ "RN et ses alliés",
    Nuance %in% c("UG", "FI", "SOC", "COM", "DVG", "ECO", "VEC") ~ "Union de la Gauche et Écolos",
    Nuance %in% c("LR", "UDI", "DVD", "UXD", "DVC") ~ "Les Républicains et ses alliés",
    Nuance %in% c("ENS", "HOR", "UDI") ~ "Ensemble",
    TRUE ~ "Autres"
  )) %>%
  group_by(Categorie) %>%
  summarise(Total_Voix = sum(Total_Voix), Pourcentage = sum(Pourcentage))

# Texte d'information au survol
resultats_groupes$hover_text <- paste(
  "Parti : ", resultats_groupes$Categorie, "<br>",
  "Nombre total de voix : ", scales::comma(resultats_groupes$Total_Voix), "<br>",
  "Pourcentage : ", round(resultats_groupes$Pourcentage, 2), "%"
)
# 1. Réorganiser l'ordre des catégories dans le tableau `resultats_groupes`
resultats_groupes <- resultats_groupes %>%
  arrange(factor(Categorie, levels = c(
    "RN et ses alliés",
    "Union de la Gauche et Écolos", 
    "Ensemble", 
    "LR et Union de la Droite" , 
    "Autres"
  )))


couleurs_groupes <- c(
  "RN et ses alliés" = "#265DAB", 
  "Union de la Gauche et Écolos" = "#CB2027",
   "Ensemble" = "#E68613",
   "Autres" = "#BEBEBE",
  "Les Républicains et ses alliés" = "#00A9FF")

p <- plot_ly(resultats_groupes, labels = ~Categorie, values = ~Pourcentage, type = 'pie',
             sort = FALSE,  # Conserve l'ordre défini dans `arrange`
             textinfo = 'label+percent', hoverinfo = 'text',
             text = ~hover_text,
             marker = list(colors = couleurs_groupes,
                           line = list(color = '#FFFFFF', width = 1)),
             insidetextorientation = 'horizontal',
             textposition = 'inside') %>% 
  layout(title = list(text = "<b>Répartition des voix par partis - Tour 1</b>", 
                      font = list(size = 20, color = 'black')),  
         showlegend = TRUE,
         legend = list(orientation = 'h', x = 0.5, xanchor = 'center', y = -0.1),  
         margin = list(t = 50, b = 20, l = 0, r = 0),
         pie = list(rotation = 180)  # Ajuster cet angle pour la disposition souhaitée
         ) %>%
  config(displayModeBar = FALSE)

p

```



# Tour 2{data-navmenu=France}

Column {data-width=1000}
-----------------------------------------------------------------------
### Inscrits
```{r}
valueBox(
  value = tags$span("43.328.508", style = "color: black;"), 
  caption = tags$span("Inscrits", style = "color: black;"),  
  icon = "fa-user", 
  color = "#00ffff"
)

```

###

```{r}
 
résultats_régions2 <- read.csv(file = "resultats-definitifs-par-regions2.csv", 
                              sep = ";", 
                              header = TRUE,
                              stringsAsFactors = FALSE, 
                              fill = TRUE)

regions_fr2 <- st_read("regions.geojson", quiet = TRUE)

data_régions2 <- résultats_régions2 %>%
  select(Libellé.région, X..Votants, X..Abstentions) %>%
  rename(region = Libellé.région, taux_part = X..Votants, taux_absenteisme = X..Abstentions) 

regions_fr2 <- regions_fr2 %>%
  left_join(data_régions2, by = c("nom" = "region"))

getColor <- function(taux_part) {
  if (taux_part < 40) {
    return(Palette1[1])
  } else if (taux_part < 50) {
    return(Palette1[2])
  } else if (taux_part < 60) {
    return(Palette1[3])
  } else if (taux_part < 70) {
    return(Palette1[4])
  } else if (taux_part < 80) {
    return(Palette1[5])
    }
}


regions_fr2$color <- sapply(regions_fr2$taux_part, getColor)

leaflet(regions_fr2) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~color,  
    color = "black", weight = 1, opacity = 1, fillOpacity = 0.7,
    highlight = highlightOptions(weight = 2, color = "white", bringToFront = TRUE),
    label = ~paste(nom, ": ", taux_part, "", sep = ""), 
    popup = ~paste(
      "<strong>Région :</strong> ", nom, "<br>",
      "<strong>Taux de participation :</strong> ", taux_part, "<br>",
      "<strong>Taux d'absentéisme :</strong> ", taux_absenteisme, "<br>"
  )) %>%
  addLegend(
    colors = Palette1, 
    labels = c("< 40%","< 50%", "< 60%", "< 70%", "< 80%"),
    opacity = 0.7, title = "Taux de participation (%)",
    position = "bottomright"
  )



```

Column {data-width=1000}
-----------------------------------------------------------

### Votants
```{r}
valueBox(
  value = tags$span("28.867.759"),  
  caption = tags$span("Votants TOUR 2"),  
  icon = "fa-envelope", 
  color = "#4040fb"
)


```

### 

```{r}
Palette1 <- c("#DAF7F0", "#82C6CC", "#3396A3", "#087D8B", "#004C63")

graph_votants2 <- ggplot(résultats_régions2, 
  aes(
    x = fct_reorder(Libellé.région, Votants),  
    y = Votants, 
    fill = Votants,  
    text = paste("Nombre de votants:", Votants)
  )
) + 
  geom_bar(stat = "identity", alpha = 0.8) +  
  coord_flip() +  
  theme_minimal() +  
  theme(
    legend.position = "none",  
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank(),  
    axis.title.x = element_blank(), 
    axis.title.y = element_text(size = 8), 
    axis.text.x = element_text(size = 5), 
    axis.text.y = element_text(size = 10, hjust = 0),
    plot.title = element_text(hjust = 0.5, size = 12),  # Taille du titre réduite
    plot.subtitle = element_text(hjust = 0.5, size = 10),  # Taille du sous-titre réduite
    plot.margin = margin(t = 20, r = 10, b = 10, l = 10)  # Marges ajustées
  ) + 
  labs(
    title = "Régions et Votes : La Bataille des Urnes",
    subtitle = "Visualisation des effectifs des votants par régions", 
    x = "", 
    y = "Nombre de votants"
  ) +
  scale_fill_gradientn(colors = Palette1) +  
  scale_y_continuous(labels = NULL)

graph_votants_interactif2 <- ggplotly(graph_votants2, tooltip = "text") %>%
  config(displayModeBar = FALSE) %>%
  layout(
    title = list(
      text = "<b>Régions et Votes : La Bataille des Urnes</b><br><sup>Visualisation des effectifs des votants par régions</sup>",
      x = 0.1,  
      xanchor = "center",
      yanchor = "top"
    )
  )
  
graph_votants_interactif2
```


Column {data-width=1000}
-----------------------------------------------------------

### Abstentions
```{r}
valueBox(
  value = tags$span("14.460.749", style = "color: black;"),  
  caption = tags$span("Abstentions TOUR 2", style = "color: black;"),  
  icon = "fa-times",
  color = "#fa5252"  
)

```

###

```{r, include=FALSE, echo=FALSE}
france_entiere2 <- read_excel("resultats-definitifs-france-entiere2.xlsx")

```

```{r}

nuances2 <- france_entiere2 %>% select(starts_with("Nuance candidat"))
voix2 <- france_entiere2 %>% select(starts_with("Voix"))

resultats_candidats2 <- data.frame(
  Nuance = unlist(nuances2),
  Voix = as.numeric(unlist(voix2))
)

resultats_candidats2 <- resultats_candidats2[resultats_candidats2$Voix > 0, ]

resultats_groupes2 <- resultats_candidats2 %>%
  group_by(Nuance) %>%
  summarise(Total_Voix = sum(Voix))

total_voix_exprimees2 <- sum(resultats_groupes2$Total_Voix)
resultats_groupes2 <- resultats_groupes2 %>%
  mutate(Pourcentage = (Total_Voix / total_voix_exprimees) * 100)

resultats_groupes2 <- resultats_groupes2 %>%
  mutate(Categorie = case_when(
    Nuance %in% c("RN", "REC", "EXD") ~ "RN et ses alliés",
    Nuance %in% c("UG", "FI", "SOC", "COM", "DVG", "ECO","VEC") ~ "Union de la Gauche et Écolos",
    Nuance %in% c("LR", "UDI", "DVD", "UXD", "DVC") ~ "LR et Union de la Droite",
    Nuance %in% c("ENS", "HOR", "UDI") ~ "Ensemble",
    TRUE ~ "Autres"
  )) %>%
    group_by(Categorie) %>%
  summarise(Total_Voix = sum(Total_Voix), Pourcentage = sum(Pourcentage))
  

resultats_groupes2$hover_text <- paste(
  "Parti : ", resultats_groupes2$Categorie, "<br>",
  "Nombre total de voix : ", comma(resultats_groupes2$Total_Voix), "<br>",
  "Pourcentage : ", round(resultats_groupes2$Pourcentage, 2), "%"
)

# 1. Réorganiser l'ordre des catégories dans le tableau `resultats_groupes`
resultats_groupes2 <- resultats_groupes2 %>%
  arrange(factor(Categorie, levels = c(
    "RN et ses alliés",
    "Union de la Gauche et Écolos", 
    "Ensemble", 
    "Autres",
    "LR et Union de la Droite" 
  )))


couleurs_groupes2 <- c(
  "RN et ses alliés" = "#265DAB", 
  "Union de la Gauche et Écolos" = "#CB2027",
   "Ensemble" = "#E68613",
   "Autres" = "#BEBEBE", 
  "Les Républicains et ses alliés" = "#00A9FF")

p <- plot_ly(resultats_groupes2, labels = ~Categorie, values = ~Pourcentage, type = 'pie',
             sort = FALSE,  # Conserve l'ordre défini dans `arrange`
             textinfo = 'label+percent', hoverinfo = 'text',
             text = ~hover_text,
             marker = list(colors = couleurs_groupes2,
                           line = list(color = '#FFFFFF', width = 1)),
             insidetextorientation = 'horizontal',
             textposition = 'inside') %>% 
  layout(title = list(text = "<b>Répartition des voix par partis - Tour 2</b>", 
                      font = list(size = 20, color = 'black')),  
         showlegend = TRUE,
         legend = list(orientation = 'h', x = 0.5, xanchor = 'center', y = -0.1),  
         margin = list(t = 50, b = 20, l = 0, r = 0),
         pie = list(rotation = 180)  # Ajuster cet angle pour la disposition souhaitée
         ) %>%
  config(displayModeBar = FALSE)

p

```




# Tour 1{data-navmenu=Indre-et-Loire}

```{r}

resultat_departements <- read.csv("resultats-definitifs-par-departements.csv",
                 sep = ";",
                 header = TRUE,
                 stringsAsFactors = FALSE,
                 fill = TRUE)

Indre_L <- resultat_departements %>% filter(Libellé.département == "Indre-et-Loire")

```


Column
----------------------------------------------

### **Taux de Participation dans la Région Centre-Val de Loire**{align=center}
```{r}
CVL <- resultat_departements %>%
  filter(Libellé.département %in% c("Indre-et-Loire",
                                     "Eure-et-Loir",
                                     "Loir-et-Cher",
                                     "Loiret",
                                     "Cher",
                                     "Indre"))


depart_fr <- st_read("departements-centre-val-de-loire.geojson", quiet = TRUE)

data_depart <- CVL %>%
  select(Libellé.département, X..Votants, X..Abstentions) %>%
  rename(region = Libellé.département, taux_part = X..Votants, taux_abstention = X..Abstentions) 


depart_fr <- depart_fr %>%
  left_join(data_depart, by = c("nom" = "region"))



# Définir une couleur fixe pour tous les départements
library(leaflet)

# Définir les couleurs
couleur_fonce <- "#003366" 
couleur_clair <- "#ADD8E6"   

# Créer la carte
leaflet(depart_fr) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~ifelse(nom == "Indre-et-Loire", couleur_fonce, couleur_clair),  
    color = "black",              
    weight = 1,                 
    opacity = 1,                 
    fillOpacity = 0.7,          
    highlight = highlightOptions(weight = 2, color = "white", bringToFront = TRUE),
    label = ~paste(nom, ": ", taux_part, "", sep = ""), 
    popup = ~paste(
      "<strong>Département :</strong> ", nom, "<br>",
      "<strong>Taux de participation :</strong> ", taux_part, "<br>",
      "<strong>Taux d'abstention :</strong> ", taux_abstention, "<br>"
    )
  ) %>%
  addLegend(
    colors = c(couleur_clair, couleur_fonce),  
    labels = c("Autres départements", "Indre-et-Loire"),
    opacity = 0.7, 
    title = "Départements", 
    position = "bottomright"
  ) 
```

### 


```{r}
taux_abs <- (Indre_L$Abstentions / Indre_L$Inscrits) * 100
taux_par <- (Indre_L$Votants / Indre_L$Inscrits) * 100
taux_blanc <- (Indre_L$Blancs / Indre_L$Votants) * 100

Jauge_blanc <- plot_ly(
  domain = list(x = c(0, 0.25), y = c(0, 1)),  
  type = "indicator",
  mode = "gauge+number",
  title = list(text = "Taux de vote blanc",font = list(size = 18, color = "black")),
  value = taux_blanc,
  gauge = list(axis = list(range = list(0, 100)), 
               bar = list(color = "#FFCC80")),
  number = list(
    prefix = "",  
    suffix = "%",  
    font = list(size = 24, color = "black", family = "Arial", weight = "bold")  
  )
)



jauge_abstention <- plot_ly(
  domain = list(x = c(0.35, 0.60), y = c(0, 1)),  
  type = "indicator",
  mode = "gauge+number",
  title = list(text = "Taux d'abstention",font = list(size = 18, color = "black")),
  value = taux_abs,
  gauge = list(
    axis = list(range = list(0, 100)),
    bar = list(color = "#F8705E")),
  number = list(
    prefix = "",  
    suffix = "%",  
    font = list(size = 24, color = "black", family = "Arial", weight = "bold")  
  )
)


jauge_participation <- plot_ly(
  domain = list(x = c(0.7, 0.95), y = c(0, 1)),  # Position dans la figure
  type = "indicator",
  mode = "gauge+number",
  title = list(text = "Taux de participation", font = list(size = 18, color = "black")),
  value = taux_par,
  gauge = list(
    axis = list(range = list(0, 100)),
    bar = list(color = "#087D3B")
  ),
  number = list(
    prefix = "",  # Aucun préfixe
    suffix = "%",  # Suffixe pour le pourcentage
    font = list(size = 24, color = "black", family = "Arial", weight = "bold")  # Gras ici
  )
)

# Combinaison des gauges dans une seule figure
fig <- subplot(Jauge_blanc,jauge_abstention,jauge_participation) %>%
  layout(title = "<b>Indicateurs des taux en Indre-et-Loire</b>",
         margin = list(l = 20, r = 20, t = 50, b = 20))%>%
  config(displayModeBar = FALSE)

fig



```


Column
------------------------------------------------


### 

```{r}

# Tour 1 
nuances <- Indre_L %>% select(starts_with("Nuance.candidat")) %>% .[, -c(10:15)]
voix <- Indre_L %>% select(starts_with("Voix")) %>% .[, -c(10:15)]
nuances <- nuances %>% select_if(~ any(!is.na(.)))
voix <- voix %>% select_if(~ any(!is.na(.)))

# Créer le data frame en utilisant les données nettoyées
resultats_candidatsL <- data.frame(
  Nuance = unlist(nuances),
  Voix = unlist(voix)
)

# Nettoyage
resultats_candidatsL$Voix <- trimws(resultats_candidatsL$Voix)
resultats_candidatsL$Voix <- gsub(" %", "", resultats_candidatsL$Voix)
resultats_candidatsL$Voix <- gsub("%", "", resultats_candidatsL$Voix)
resultats_candidatsL$Voix <- gsub(",", ".", resultats_candidatsL$Voix)

# Convertir la colonne Voix en numérique et supprimer les NA
resultats_candidatsL$Voix <- suppressWarnings(as.numeric(resultats_candidatsL$Voix))
resultats_candidatsL <- resultats_candidatsL %>% filter(!is.na(Voix))


resultats_groupesL <- resultats_candidatsL %>%
  group_by(Nuance) %>%
  summarise(Total_Voix = sum(Voix, na.rm = TRUE))


total_voix_exprimeesL <- sum(resultats_groupesL$Total_Voix)
resultats_groupesL <- resultats_groupesL %>%
  mutate(Pourcentage = (Total_Voix / total_voix_exprimeesL) * 100)


# Harmoniser les catégories et regrouper les voix
resultats_groupesL <- resultats_groupesL %>%
  mutate(Categorie = case_when(
    Nuance %in% c("UG", "DVG") ~ "Union de la Gauche",    
    Nuance %in% c("RN", "REC") ~ "Rassemblement National et Reconquête",
    Nuance %in% c("LR", "UXD") ~ "Les républicains et alliés",
    Nuance %in% c("ENS") ~ "Ensemble",
    Nuance %in% c("EXG") ~ "Extrême Gauche",
    Nuance %in% c("DIV") ~ "Divers et Indépendants"
  )) %>%
  group_by(Categorie) %>%
  summarise(Total_Voix = sum(Total_Voix), Pourcentage = sum(Pourcentage))

resultats_groupesL$hover_text <- paste(
  "Parti : ", resultats_groupesL$Categorie, "<br>",
  "Nombre total de voix : ", scales::comma(resultats_groupesL$Total_Voix), "<br>",
  "Pourcentage : ", round(resultats_groupesL$Pourcentage, 2), "%"
)

# Réorganiser l'ordre des catégories pour contrôler la disposition dans le diagramme
resultats_groupesL <- resultats_groupesL %>%
  arrange(factor(Categorie, levels = c(
    "Ensemble",
    "Union de la Gauche",
    "Rassemblement National <br> et Reconquête",
    "Les républicains et alliés", 
    "Divers et Indépendants", 
     "Extrême Gauche"  
  )))

# Définition des couleurs mises à jour pour correspondre aux catégories
couleurs_groupes1 <- c(
  "Ensemble" = "#E68613",
  "Union de la Gauche" = "#CB2027",
  "Les républicains et UXD" = "#00A9FF",   
  "Divers et Indépendants" = "#BEBEBE", 
  "Extrême Gauche" = "pink", 
  "Rassemblement National <br> et Reconquête" = "#265DAB")

# Création du diagramme circulaire avec l'angle de rotation
p <- plot_ly(resultats_groupesL, labels = ~Categorie, values = ~Pourcentage, type = 'pie',
             sort = FALSE,  # Conserve l'ordre défini dans `arrange`
             textinfo = 'label+percent', hoverinfo = 'text',
             text = ~hover_text,
             marker = list(colors = couleurs_groupes1,
                           line = list(color = '#FFFFFF', width = 1)),
             insidetextorientation = 'horizontal',
             textposition = 'inside',
             rotation = 180  # Ajuster cet angle pour la disposition souhaitée
) %>% 
  layout(title = list(text = "<b>Répartition des voix par partis - Tour 1<b>", 
                      font = list(size = 20, color = 'black')),  
         showlegend = TRUE,
         legend = list(orientation = 'h', x = 0.5, xanchor = 'center', y = -0.1),  
         margin = list(t = 50, b = 20, l = 0, r = 0)) %>%
  config(displayModeBar = FALSE)

p

```

# Tour 2{data-navmenu=Indre-et-Loire}



```{r}
resultat_departements2 <- read.csv("resultats-definitifs-par-departements2.csv",
                 sep = ";",
                 header = TRUE,
                 stringsAsFactors = FALSE, 
                 fill = TRUE)

Indre_L2 <- resultat_departements2 %>% filter(Libellé.département == "Indre-et-Loire")

```
Column
----------------------------------------------


### **Taux de Participation dans la Région Centre-Val de Loire**{align=center}
```{r}
CVL2 <- resultat_departements2 %>%
  filter(Libellé.département %in% c("Indre-et-Loire",
                                     "Eure-et-Loir",
                                     "Loir-et-Cher",
                                     "Loiret",
                                     "Cher",
                                     "Indre"))


depart_fr2 <- st_read("departements-centre-val-de-loire.geojson", quiet = TRUE)

data_depart2 <- CVL2 %>%
  select(Libellé.département, X..Votants, X..Abstentions) %>%
  rename(region = Libellé.département, taux_part = X..Votants, taux_abstention = X..Abstentions) 


depart_fr2 <- depart_fr2 %>%
  left_join(data_depart2, by = c("nom" = "region"))



# Définir une couleur fixe pour tous les départements
library(leaflet)

# Définir les couleurs
couleur_fonce <- "#003366" 
couleur_clair <- "#ADD8E6"   



# Créer la carte
leaflet(depart_fr2) %>%
  addTiles() %>%
  addPolygons(
    fillColor = ~ifelse(nom == "Indre-et-Loire", couleur_fonce, couleur_clair),  
    color = "black",              
    weight = 1,                 
    opacity = 1,                 
    fillOpacity = 0.7,          
    highlight = highlightOptions(weight = 2, color = "white", bringToFront = TRUE),
    label = ~paste(nom, ": ", taux_part, "", sep = ""), 
    popup = ~paste(
      "<strong>Département :</strong> ", nom, "<br>",
      "<strong>Taux de participation :</strong> ", taux_part, "<br>",
      "<strong>Taux d'abstention :</strong> ", taux_abstention, "<br>"
    )
  ) %>%
  addLegend(
    colors = c(couleur_clair, couleur_fonce),  
    labels = c( "Autres départements", "Indre-et-Loire"),
    opacity = 0.7, 
    title = "Départements", 
    position = "bottomright")
```

###

```{r}

taux_blanc2 <- (Indre_L2$Blancs / Indre_L2$Votants) * 100
taux_abs2 <- (Indre_L2$Abstentions / Indre_L2$Inscrits) * 100
taux_par2 <- (Indre_L2$Votants / Indre_L2$Inscrits) * 100

jauge_blanc2 <- plot_ly(
  domain = list(x = c(0, 0.25), y = c(0, 1)), 
  type = "indicator",
  mode = "gauge+number",
  title = list(text = "Taux de vote blanc",font = list(size = 18, color = "black")),
  value = taux_blanc2,
  gauge = list(axis = list(range = list(0, 100)), 
               bar = list(color = "#FFCC80")),
  number = list(
    prefix = "",  
    suffix = "%", 
    font = list(size = 24, color = "black", family = "Arial", weight = "bold")  
  )
)



jauge_abstention2 <- plot_ly(
  domain = list(x = c(0.35, 0.60), y = c(0, 1)),  
  type = "indicator",
  mode = "gauge+number",
  title = list(text = "Taux d'abstention",font = list(size = 18, color = "black")),
  value = taux_abs2,
  gauge = list(
    axis = list(range = list(0, 100)),
    bar = list(color = "#F8705E")),
  number = list(
    prefix = "",  
    suffix = "%",  
    font = list(size = 24, color = "black", family = "Arial", weight = "bold") 
  )
)




jauge_participation2 <- plot_ly(
  domain = list(x = c(0.7, 0.95), y = c(0, 1)),  
  type = "indicator",
  mode = "gauge+number",
  title = list(text = "Taux de participation", font = list(size = 18, color = "black")),
  value = taux_par2,
  gauge = list(
    axis = list(range = list(0, 100)),
    bar = list(color = "#087D3B")
  ),
  number = list(
    prefix = "",  
    suffix = "%",  
    font = list(size = 24, color = "black", family = "Arial", weight = "bold")  
  )
)

# Combinaison des gauges dans une seule figure
fig <- subplot(jauge_blanc2,jauge_abstention2,jauge_participation2) %>%
  layout(title = "<b>Indicateurs des taux en Indre-et-Loire</b>",
         margin = list(l = 20, r = 20, t = 50, b = 20))%>%
  config(displayModeBar = FALSE)

fig
```



Column
----------------------------------------------

###



```{r}
# Filtrage pour Tour 2 avec uniquement les nuances UG, ENS, RN, UXD
nuances2 <- Indre_L2 %>% select(starts_with("Nuance.candidat"))
voix2 <- Indre_L2 %>% select(starts_with("Voix"))

# Sélection de nuances et voix sans exclusion de colonnes
nuances2 <- nuances2 %>% select_if(~ any(!is.na(.)))
voix2 <- voix2 %>% select_if(~ any(!is.na(.)))

# Création du data frame et nettoyage
resultats_candidatsL2 <- data.frame(
  Nuance = unlist(nuances2),
  Voix = as.numeric(unlist(voix2))
)

resultats_candidatsL2 <- resultats_candidatsL2 %>% filter(!is.na(Voix) & Voix > 0)

# Agrégation par Nuance et calcul des pourcentages
resultats_groupesL2 <- resultats_candidatsL2 %>%
  filter(Nuance %in% c("UG", "ENS", "RN", "UXD")) %>%
  group_by(Nuance) %>%
  summarise(Total_Voix = sum(Voix)) %>%
  mutate(Pourcentage = (Total_Voix / sum(Total_Voix)) * 100)

# Définition des catégories
resultats_groupesL2 <- resultats_groupesL2 %>%
  mutate(Categorie = case_when(
    Nuance == "RN" ~ "Rassemblement National",  
    Nuance == "ENS" ~ "Ensemble",
    Nuance == "UG" ~ "Union de la Gauche",
    Nuance == "UXD" ~ "Union de la droite",
  )) %>%
  group_by(Categorie) %>%
  summarise(Total_Voix = sum(Total_Voix), Pourcentage = sum(Pourcentage))

# Texte au survol et couleurs
resultats_groupesL2$hover_text <- paste(
  "Parti : ", resultats_groupesL2$Categorie, "<br>",
  "Nombre total de voix : ", scales::comma(resultats_groupesL2$Total_Voix), "<br>",
  "Pourcentage : ", round(resultats_groupesL2$Pourcentage, 2), "%"
)

# Réorganiser les catégories pour le contrôle de la disposition dans le diagramme


resultats_groupesL2 <- resultats_groupesL2 %>%
  arrange(factor(Categorie, levels = c(
    
      "Ensemble",
     "Union de la Gauche", 
     "Union de la droite",
     "Rassemblement National"
  )))

# Couleurs mises à jour pour correspondre aux catégories
couleurs_groupes2 <- c( 
  "Ensemble" = "#E68613",
  "Union de la Gauche" = "#CB2027",
  "Union de la droite" = "#00A9FF",
  "Rassemblement National" = "#265DAB"
)

# Création du diagramme circulaire avec contrôle de la rotation
p <- plot_ly(resultats_groupesL2, labels = ~Categorie, values = ~Pourcentage, type = 'pie',
             sort = FALSE,  # Maintient l'ordre défini dans `arrange`
             textinfo = 'label+percent', hoverinfo = 'text',
             text = ~hover_text,
             marker = list(colors = couleurs_groupes2,
                           line = list(color = '#FFFFFF', width = 1)),
             insidetextorientation = 'horizontal',
             textposition = 'inside',
             rotation = 180  # Ajustez cet angle pour une position optimale des segments
) %>% 
  layout(title = list(text = "<b>Répartition des voix par partis - Tour 2<b>", 
                      font = list(size = 20, color = 'black')),  
         showlegend = TRUE,
         legend = list(orientation = 'h', x = 0.5, xanchor = 'center', y = -0.1),  
         margin = list(t = 50, b = 20, l = 0, r = 0)) %>%
  config(displayModeBar = FALSE)

# Afficher le graphique
p

```



# Base de Données Utilisées

### **Cartographie** 

```{r}
election_data <- data.frame(
  Election = c("France Tour 1", "France Tour 2", "Indre-et-Loire Tour 1", "Indre-et-Loire Tour 2"),
  Type_de_donnees = c("Résultats par régions", "Résultats par régions", "Résultats par département", "Résultats par département"),
  Source_fichier_resultats = c(
    "https://www.data.gouv.fr/fr/datasets/elections-legislatives-des-30-juin-et-7-juillet-2024-resultats-definitifs-du-1er-tour/",
    "https://www.data.gouv.fr/fr/datasets/elections-legislatives-des-30-juin-et-7-juillet-2024-resultats-definitifs-du-2nd-tour/",
    "https://www.data.gouv.fr/fr/datasets/elections-legislatives-des-30-juin-et-7-juillet-2024-resultats-definitifs-du-1er-tour/",
    "https://www.data.gouv.fr/fr/datasets/elections-legislatives-des-30-juin-et-7-juillet-2024-resultats-definitifs-du-2nd-tour/"
  ),
  Source_fichier_JSON = c(
    "https://www.data.gouv.fr/fr/datasets/contours-des-communes-de-france-simplifie-avec-regions-et-departement-doutre-mer-rapproches/",
    "https://www.data.gouv.fr/fr/datasets/contours-des-communes-de-france-simplifie-avec-regions-et-departement-doutre-mer-rapproches/",
    "https://github.com/gregoiredavid/france-geojson/tree/master/regions/centre-val-de-loire",
    "https://github.com/gregoiredavid/france-geojson/tree/master/regions/centre-val-de-loire"
  )
)

# Utiliser knitr::kable pour afficher proprement le tableau
kable(election_data, format = "markdown")
```





### **Diagramme Circulaire**  

```{r}

election_data <- data.frame(
  Election = c("France Tour 1", "France Tour 2", "Indre-et-Loire Tour 1", "Indre-et-Loire Tour 2"),
  Type_de_donnees = c("Résultats pour toute la France", "Résultats pour toute la France", "Résultats par département", "Résultats par département"),
  Source_fichier_resultats = c(
    "https://www.data.gouv.fr/fr/datasets/elections-legislatives-des-30-juin-et-7-juillet-2024-resultats-definitifs-du-1er-tour/",
    "https://www.data.gouv.fr/fr/datasets/elections-legislatives-des-30-juin-et-7-juillet-2024-resultats-definitifs-du-2nd-tour/",
    "https://www.data.gouv.fr/fr/datasets/elections-legislatives-des-30-juin-et-7-juillet-2024-resultats-definitifs-du-1er-tour/",
    "https://www.data.gouv.fr/fr/datasets/elections-legislatives-des-30-juin-et-7-juillet-2024-resultats-definitifs-du-2nd-tour/"
  )
)

# Utiliser knitr::kable pour afficher proprement le tableau
kable(election_data, format = "markdown")
```



### **Dashboard réalisé par :**

```{r}
# Créer un tableau avec les créateurs du dashboard
creators_data <- data.frame(
  Nom = c("Hasfa Mousalli", "Imane Lemkhayer", "Ilayda Yilmaz"),
  Lien_LinkedIn = c(
    "[Hasfa Mousalli](http://www.linkedin.com/in/hafsa-mousalli)",
    "[Imane Lemkhayer](http://www.linkedin.com/in/imane-lemkhayer)",
    "[Ilayda Yilmaz](http://www.linkedin.com/in/ilayda-yilmaz-576ba432a)"
  )
)

# Afficher le tableau des créateurs avec knitr::kable
library(knitr)
kable(creators_data, format = "markdown", col.names = c("Nom", "Profil LinkedIn"))

```



